version: "3.9"
services:
  shared-pad:
    build: .
    image: shared-pad:latest
    container_name: shared-pad
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - sharedpad-data:/usr/src/app/data
    restart: unless-stopped
volumes:
  sharedpad-data:
